### ISSUE TITLE
Perform smear correction

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/kadenza#1]
It would be nice if `kadenza` was able to correct the TPF files it creates for smear. (Smear is the extra flux in pixels that result from the lack of shutter on board Kepler.).

Information on the smear correction is available here:
- Paper `Pixel-Level Calibration in the Kepler Science Operations Center Pipeline` by Quintana et al
- Kepler Data Processing Handbook, Section 5.3

In brief, the smear correction is a constant value that needs to be subtracted from every pixel in a read-out column.  The data required to correct for smear is stored in the so-called Collateral Data Files (`*lcs-col.fits`); these contain binned versions of per-column virtual and masked smear pixels. Typically an average of virtual+masked is used, unless a bright star has bled into the smear pixels.

**Comment by barentsen** [comment]
The way this should probably work is to have one extra parameter, e.g. `--collateral-mapping kplr2016068153039-000-000_lcc.fits` added to the command line API?

Kadenza will then automatically assume that the user wants to perform smear correction, and look for collateral cadence data files with filename `cadencefile.replace('-targ.fits', '-col.fits')` (ie this assumes that a collateral cadence file is in the same directory as the corresponding science cadence file, with the same prefix).

The easiest way to implement this may be to add a method `CollateralData.get_smear_at_column([list of column numbers])`.  The method will return a list of smear values to subtract from each column.

We will also need a test to verify that this really works.

**Comment by mirca** [comment]
@barentsen I think this can be closed as well?

**Comment by barentsen** [comment]
👍
