### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mar-ses** [KeplerGO/kadenza#2]
When trying to use kadenza (on the c9 raw dataset) I'm getting a FileNotFound error:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/lib/python3.5/site-packages/kadenza-2.0.1-py3.5.egg/kadenza/header-templates/tpf-ext0-header.txt'
`

I installed kadenza as suggested in the instructions, although I later moved the initial kadenza dir (which contains the `setup.py` to a new location), although I'm not sure why that would cause the error. 

Happens on Linux 16.10 and 14.04, and using python 3.5 and 3.4.
Looking at my file structure, there is no `header_templates` dir in my `'/home/user/anaconda3/lib/python3.5/site-packages/kadenza-2.0.1-py3.5.egg/kadenza/'` directory. It only contains `__pycache__`, `__init__.py`, `kadenza.py` and `version.py`. 

I tried reinstalling it with a python 3.4 environment, same problem, the setup doesn't seem to create those header templates.

**Comment by mar-ses** [comment]
I found a header_templates dir in the `kadenza` directory I cloned of githup (with the `setup.py`) and copied it to the required location. That seems to have fixed it.

**Comment by barentsen** [comment]
Right, I believe the `setup()` function in `setup.py` is missing a `data_files` argument to ensure that the `header-templates` directory is actually installed. Oops.

A temporary workaround is to install using `python setup.py develop`.

**Comment by mar-ses** [comment]
Thanks, also one more thing, it's unrelated but don't want to start another thread. When I use kadenza to extract raw data, it produces the TIME and RAW_CNTS tables, but it also for some reason produces FLUX_ERR (but not FLUX). I was under the impression that this was something that is calculated after calibration and all that. So how is FLUX_ERR calculated?

**Comment by barentsen** [comment]
@mar-ses I believe the `FileNotFoundError` is now resolved.  Please verify if you get the chance.

The kadenza-produced TPFs are intended to have FLUX and FLUX_ERR columns that contain only `NaN` values, just so that the format of the TPFs is similar to the calibrated products (i.e. same columns).
